<script lang="ts">
	import type { PageData } from './$types';
	import { enhance } from '$app/forms';
	import { GalleryVerticalEnd } from 'lucide-svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import Label from '$lib/components/ui/label/label.svelte';
	import * as Card from '$lib/components/ui/card';
	import { Progress } from '$lib/components/ui/progress';
	import { Separator } from '$lib/components/ui/separator';
	export let data: PageData;
	export let form: PageData;
	import * as RadioGroup from '$lib/components/ui/radio-group';

	$: questions = form?.questions ? form.questions : [];

	let answers: string[] = [];

	export const snapshot: import('./$types').Snapshot<string[]> = {
		capture: () => answers,
		restore: (value: string[]) => {
			value.forEach((v) => answers.push(v));
		}
	};
</script>

<main class="flex h-screen w-screen flex-col p-3">
	{#if !questions.length}
		<form action="?/generate" method="post" use:enhance>
			<Card.Root class="w-full">
				<Card.Header>
					<div class="flex justify-between">
						<div class="align-text-middle place-middle flex gap-4 align-middle">
							<div>
								<GalleryVerticalEnd />
							</div>
							<div>
								<Card.Title>Interview Process</Card.Title>
								<Card.Description>Interview process description.</Card.Description>
							</div>
						</div>
						<div class="flex w-[250px] gap-4">
							<Progress value={33} />
							<h4 class="scroll-m-20 text-xl font-semibold tracking-tight">1/10</h4>
						</div>
					</div>
				</Card.Header>
				<Separator class="mb-8" />
				<Card.Content>
					<div class="grid w-full items-center gap-4">
						<div class="flex flex-col space-y-2">
							<h1 class="text-xl font-semibold tracking-tight">
								This is a question generated by ...
							</h1>
						</div>
						<Separator class="mb-8" />
						<div class="flex flex-col space-y-2">
							<RadioGroup.Root value="comfortable">
								<div class="mb-6 flex items-center space-x-2">
									<RadioGroup.Item value="default" id="r1" />
									<Label for="r1">This is just an answer, okay!</Label>
								</div>
								<div class="mb-6 flex items-center space-x-2">
									<RadioGroup.Item value="comfortable" id="r2" />
									<Label for="r2">This is just an answer, okay!</Label>
								</div>
								<div class="mb-6 flex items-center space-x-2">
									<RadioGroup.Item value="compact" id="r3" />
									<Label for="r3">This is just an answer, okay!</Label>
								</div>
								<RadioGroup.Input name="spacing" />
							</RadioGroup.Root>
						</div>
					</div>
				</Card.Content>
				<Separator class="mb-8" />
				<Card.Footer class="flex justify-end gap-2">
					<Button variant="outline">Previous</Button>
					<Button>Next</Button>
				</Card.Footer>
			</Card.Root>
		</form>
	{:else}
		<p>Questions:</p>
		{#each questions as { question }, i}
			<p>
				<span>{i + 1}.</span>
				{question}
			</p>
		{/each}
	{/if}
</main>
