name: 'Deploy SvelteKit Application to Vercel'

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - production
        paths:
            - 'application/**'
            - '!appliction/*.md'
        paths-ignore:
            - 'docs/**'
            - 'README.md'
            - 'backend/**'

jobs:
    Deploy:
        runs-on: 'ubuntu-latest'
        steps:
            - uses: 'actions/checkout@v2'

            - name: 'Install Vercel CLI'
              run: pnpm install -g vercel@canary

            - name: 'Pull Vercel Environment Information'
              run:  vercel pull --yes --environment=${{ env.VERCEL_ENVIRONMENT_ID }} --token=${{ secrets.VERCEL_TOKEN }}

            - name: 'Build SvelteKit Application'
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            
            - name: 'Deploy SvelteKit Application to Vercel'
              run: vercel deploy --prebuild --prod --token=${{ secrets.VERCEL_TOKEN }}

