name: 'Continuous Integration | SvelteKit Application'

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - production

jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

# TODO: Create steps for lint and format
# TODO: Create branch ruls that main and development branches are not allowed to merge until this job is successful